language: objective-c
osx_image: xcode10.1

install:
  - bundle install
  - bundle exec pod repo update --silent
  - bundle exec pod install

script:
  - Pods/SwiftLint/swiftlint
  - bundle exec fastlane test
